name:                HeatSolver
version:             0.1.0.0
github:              "riz0id/HeatSolver"
license:             BSD3

extra-source-files:
- README.md

description: 2d heat simulation

dependencies:
- base                   >= 4.7 && < 5
- accelerate             ==1.3.*
- accelerate-llvm-native ==1.3.*
- colour-accelerate
- gloss
- gloss-accelerate
- accelerate-io-bmp      >= 0.1

library:
  source-dirs: lib

tests:
  HeatSolver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HeatSolver
