resolver: lts-13.25

nix:
  enable: true
  pure: false
  packages: [mesa_glu freeglut libffi]
  
flags:
  llvm-hs:
    shared-llvm: true

packages:
- .

extra-deps:
- git:    https://github.com/tmcdonell/accelerate.git
  commit: 1010d97f8cc8cbecff28200cf6e176455769c644

- git:    https://github.com/tmcdonell/accelerate-llvm.git
  commit: 60b0ebc38549e887159e0bec7493fad2231a2550
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx

- git:    https://github.com/tmcdonell/accelerate-io.git
  commit: e83461b194bb046a6f129a6be7f0e865653ed365
  subdirs:
    - accelerate-io
    - accelerate-io-array
    - accelerate-io-bmp
    - accelerate-io-bytestring
    - accelerate-io-JuicyPixels
    - accelerate-io-repa
    - accelerate-io-vector

- git:    https://github.com/tmcdonell/accelerate-fft.git
  commit: 1ecec4e16ca30d87ee8d10a63276e02f55f39031

- git:    https://github.com/tmcdonell/colour-accelerate.git
  commit: edc575cc6a810f5cce8d4b4423ef3968f30a93a3

- git:    https://github.com/tmcdonell/gloss-accelerate.git
  commit: de4da479dfa236f4b7c08348cfc7e9fef70476ea

- git:    https://github.com/tmcdonell/gloss-raster-accelerate.git
  commit: a2f29879d87222f68a8b8e06fa8f1960d7e5a671

- git:    https://github.com/tmcdonell/lens-accelerate.git
  commit: b74eb8098735b1ad6cff3c5655af03d3f29b9f8e

- git:    https://github.com/tmcdonell/linear-accelerate.git
  commit: 7d3bb1d40cdcc75f2f658c31b2eb7541c949e52e

- git:    https://github.com/tmcdonell/mwc-random-accelerate.git
  commit: e840871e2edbc583bc90230b1bb9d9452e89d3d6

- cuda-0.10.1.0
- hedgehog-1.0
- llvm-hs-8.0.0
- llvm-hs-pure-8.0.0
- normaldistribution-1.1.0.3
- tasty-hedgehog-1.0.0.1